/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.main.java.org.example;
import app.src.main.java.org.example.Classes.*;
import java.lang.reflect.Proxy;
public class App {


    public static void main(String[] args) {
        Man mohan=new Man("Mohan",30,"delhi","India")
        ClassLoader mohanClassLoader=mohan.getClass().getClassLoader();
        Class[] interfaces=mohan.getClass.getInterfaces();
        Person proxyMohan=(Person)Proxy.newProxyInstance(mohanClassLoader,interfaces,new PersonInvocationHandler(mohan));
        proxyMohan.introduce(mohan.getName());   }

}
